version: "3"
services:
  gitlab:
    image: gitlab/gitlab-ce:16.4.0-ce.0
    container_name: gitlab-ce
    restart: always
    hostname: "192.168.34.240" # Set your custom hostname here
    ports:
      - "8929:8929" # Map GitLab port to your desired port
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://192.168.34.240:8929'  # Set your custom external URL here
        registry_external_url 'http://192.168.34.240:5000' # Adjust as needed
    volumes:
      - ./config:/etc/gitlab
      - ./data:/var/opt/gitlab
      - ./logs:/var/log/gitlab
    networks:
      - gitlab_network

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: always
    volumes:
      - ./runner-config:/etc/gitlab-runner
    networks:
      - gitlab_network

  docker-registry:
    image: registry:2
    container_name: docker-registry
    restart: always
    ports:
      - "5000:5000"
    volumes:
      # - ./volume:/var/lib/registry
      - ./registry-data:/var/lib/registry
    networks:
      - gitlab_network

  docker-registry-ui:
    image: konradkleine/docker-registry-frontend:v2
    container_name: docker-registry-ui
    restart: always
    depends_on:
      - docker-registry
    ports:
      - "8080:80"
    environment:
      ENV_DOCKER_REGISTRY_HOST: docker-registry
      ENV_DOCKER_REGISTRY_PORT: 5000
    networks:
      - gitlab_network

networks:
  gitlab_network:
    driver: bridge
